### Authentification pour récupérer le JWT
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "adminpass"
}

### Exemple d'appel protégé avec token (remplace {{jwt_token}} après login)

GET http://localhost:8080/api/reservations
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0NTY3OTE1OCwiZXhwIjoxNzQ1NzE1MTU4fQ.uVXAH_f8HO3-OJ8bqzklRSRhksY1KYMmVFCYDNk96Eo
Accept: application/json

### Exemple POST création réservation (protégé)

POST http://localhost:8080/api/reservations
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0NTY3OTE1OCwiZXhwIjoxNzQ1NzE1MTU4fQ.uVXAH_f8HO3-OJ8bqzklRSRhksY1KYMmVFCYDNk96Eo
Content-Type: application/json

{
  "passengerName": "omega de Dschang",
  "destination": "Dschang",
  "date": "2025-05-01"
}

### Créer une invitation
POST http://localhost:8080/api/invitations?email=andersonmetsanoum@gmail.com
Content-Type: application/json
##Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0NTY4MjA4OCwiZXhwIjoxNzQ1NzE4MDg4fQ.bPAEK7AP_0NkYqiOXj9kAnGU4w353r2r3X9lK3yJ8bo

### Valider une invitation avec son token
GET http://localhost:8080/api/invitations/validate?token=2732080f-d2c3-4979-a9eb-33ebef72e81d
Content-Type: application/json

### Réserver en tant qu'invité
POST http://localhost:8080/guest/reserve?email=guest@example.com&passengerName=John Doe&destination=China&date=2025-05-01

### Convertir une session invitée en compte
POST http://localhost:8080/guest/register?email=guest@example.com

### Test abonnement avec un body JSON

POST http://localhost:8080/api/billing/subscribe
##Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0NTY5MDcwNiwiZXhwIjoxNzQ1NzI2NzA2fQ.SdbzMOmILtNsLQMsAbWDdl9Uo8JEffoVLB8LnlsgJAU
Content-Type: application/json

{
  "agencyName": "BestTravel",
  "planType": "trial"
}


###

### Vérifier que l'agence est encore abonnée (True attendu)
GET http://localhost:8080/api/billing/validate?agencyName=BestTravel
Accept: application/json

